"""ratctl CLI — fuzz your verifier before an RL agent does."""

from __future__ import annotations

import re
import sys

import click

from ratctl import __version__


@click.group()
@click.version_option(version=__version__, prog_name="ratctl")
def main():
    """ratctl - Reward Audit Tool.

    Fuzz your verifier before an RL agent does.

    Audit RL environment verifiers and reward functions for
    reward-hacking exploitability. Supports OpenEnv, verifiers-spec,
    and Gymnasium environments.
    """


@main.command()
@click.argument("path", type=click.Path(exists=True))
@click.option(
    "--fail-on",
    type=str,
    default=None,
    help="Fail (exit 1) if condition is met. Format: 'gameability>N' where N is 0.0-1.0. "
    "Example: --fail-on 'gameability>0.3'",
)
@click.option(
    "--format",
    "output_format",
    type=click.Choice(["rich", "json", "text"]),
    default="rich",
    help="Output format.",
)
@click.option(
    "--output",
    "-o",
    type=click.Path(),
    default=None,
    help="Write report to file instead of stdout.",
)
@click.option(
    "--env-format",
    type=click.Choice(["openenv", "verifiers", "gymnasium", "raw"]),
    default=None,
    help="Force environment format instead of auto-detecting.",
)
@click.option(
    "--dynamic",
    "-d",
    is_flag=True,
    default=False,
    help="Enable dynamic LLM-driven fuzzing (requires Ollama or --frontier).",
)
@click.option(
    "--frontier",
    is_flag=True,
    default=False,
    help="Use paid API (OpenAI/Anthropic) instead of local Ollama for fuzzing.",
)
@click.option(
    "--samples",
    type=int,
    default=5,
    help="Number of exploit attempts for dynamic fuzzing (default: 5).",
)
@click.option(
    "--timeout",
    type=int,
    default=30,
    help="Per-attempt sandbox timeout in seconds (default: 30).",
)
@click.option(
    "--model",
    type=str,
    default=None,
    help="Override the default LLM model for dynamic fuzzing.",
)
def audit(
    path: str,
    fail_on: str | None,
    output_format: str,
    output: str | None,
    env_format: str | None,
    dynamic: bool,
    frontier: bool,
    samples: int,
    timeout: int,
    model: str | None,
):
    """Audit an RL environment for reward-hacking exploitability.

    PATH is the path to the environment directory or file to audit.

    \b
    Examples:
      ratctl audit ./my_env
      ratctl audit ./my_env --fail-on 'gameability>0.3'
      ratctl audit ./my_env --format json -o report.json
      ratctl audit ./verifier.py --env-format raw
      ratctl audit ./my_env --dynamic
      ratctl audit ./my_env --dynamic --frontier --samples 10
    """
    from ratctl.analyzer import audit as run_audit
    from ratctl.report import render_report

    try:
        score = run_audit(
            path,
            format_override=env_format,
            dynamic=dynamic,
            frontier=frontier,
            model=model,
            samples=samples,
            timeout=timeout,
        )
    except FileNotFoundError as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(2)
    except Exception as e:
        click.echo(f"Error during audit: {e}", err=True)
        sys.exit(2)

    # Render report
    report = render_report(score, fmt=output_format, output=output)

    if output:
        click.echo(f"Report written to {output}")
    else:
        try:
            click.echo(report)
        except UnicodeEncodeError:
            sys.stdout.buffer.write(report.encode("utf-8", errors="replace") + b"\n")

    # Check fail-on threshold
    if fail_on:
        threshold = _parse_threshold(fail_on)
        if threshold is not None and score.exceeds_threshold(threshold):
            click.echo(
                f"\nFAIL: Gameability score {score.gameability_score}/100 "
                f"exceeds threshold {threshold:.0%}",
                err=True,
            )
            sys.exit(1)

    # Exit 0 if no threshold exceeded
    sys.exit(0)


@main.command()
@click.argument("path", type=click.Path(exists=True))
@click.option(
    "--format",
    "output_format",
    type=click.Choice(["rich", "json", "text"]),
    default="rich",
    help="Output format.",
)
def report(path: str, output_format: str):
    """Re-render a previously saved JSON report.

    PATH is the path to a JSON report file generated by 'ratctl audit --format json'.
    """
    import json
    from pathlib import Path

    try:
        data = json.loads(Path(path).read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as e:
        click.echo(f"Error reading report: {e}", err=True)
        sys.exit(2)

    # Re-render in requested format
    if output_format == "json":
        click.echo(json.dumps(data, indent=2))
    else:
        # Pretty-print the data
        click.echo(f"Gameability Score: {data.get('gameability_score', '?')}/100")
        click.echo(f"Total Findings: {data.get('total_findings', '?')}")
        for class_name, cs in data.get("class_scores", {}).items():
            if cs.get("finding_count", 0) > 0:
                click.echo(f"\n[{class_name.upper()}] - {cs['finding_count']} finding(s)")
                for f in cs.get("findings", []):
                    click.echo(f"  [{f['severity'].upper()}] {f['title']}")
                    click.echo(f"    {f['file_path']}:{f.get('line_number', '?')}")


@main.command()
@click.argument("path", type=click.Path(exists=True), default="benchmarks")
@click.option(
    "--format",
    "output_format",
    type=click.Choice(["markdown", "json", "text"]),
    default="markdown",
    help="Benchmark report output format.",
)
@click.option(
    "--threshold",
    type=float,
    default=0.25,
    help="Gameability threshold for exploit detection (default: 0.25).",
)
@click.option(
    "--output",
    "-o",
    type=click.Path(),
    default=None,
    help="Write report to file instead of stdout.",
)
def benchmark(path: str, output_format: str, threshold: float, output: str | None):
    """Run an empirical validation benchmark across a suite of environments.

    Calculates Detection Recall (TPR), Specificity (TNR), Precision, and Accuracy
    against known hackable environments and clean controls.
    """
    import json
    from ratctl.benchmark import run_benchmark_suite

    try:
        summary = run_benchmark_suite(path, threshold=threshold)
    except Exception as e:
        click.echo(f"Error during benchmark: {e}", err=True)
        sys.exit(2)

    if output_format == "json":
        report_text = json.dumps(summary.to_dict(), indent=2)
    elif output_format == "markdown":
        report_text = summary.format_markdown()
    else:
        report_text = (
            f"Recall (TPR): {summary.recall:.1%} ({summary.true_positives}/{summary.vulnerable_tasks})\n"
            f"Specificity (TNR): {summary.specificity:.1%} ({summary.true_negatives}/{summary.clean_tasks})\n"
            f"Precision: {summary.precision:.1%}\n"
            f"Accuracy: {summary.accuracy:.1%}\n"
            f"Total Tasks: {summary.total_tasks}"
        )

    if output:
        from pathlib import Path
        Path(output).write_text(report_text, encoding="utf-8")
        click.echo(f"Benchmark report written to {output}")
    else:
        click.echo(report_text)


@main.command()
@click.argument("log_path", type=click.Path(exists=True), default="logs/run.jsonl")
@click.option("--follow", "-f", is_flag=True, help="Follow log output in real time.")
def show(log_path: str, follow: bool):
    """Inspect live runtime verifier trajectory logs (JSONL)."""
    from ratctl.watch import read_logs

    events = read_logs(log_path)
    if not events:
        click.echo(f"No logged verifier events found in {log_path}")
        return

    click.echo(f"=== RATCTL RUNTIME TRAJECTORY LOGS ({len(events)} events) ===")
    for e in events:
        status = "[PASS]" if e.get("passed") else "[FAIL]"
        reward = e.get("reward", 0.0)
        ms = e.get("duration_ms", 0.0)
        verifier = e.get("verifier_name", "verifier")
        click.echo(f"Step {e.get('step'):<4} | {status} reward={reward:<5.2f} | {ms:<6.1f}ms | {verifier}")


@main.command()
@click.argument("log_path", type=click.Path(exists=True), default="logs/run.jsonl")
def summary(log_path: str):
    """Display aggregate statistics over runtime verifier JSONL logs."""
    from ratctl.watch import summarize_logs

    stats = summarize_logs(log_path)
    click.echo("=== RATCTL RUNTIME TRAJECTORY SUMMARY ===")
    click.echo(f"Total Verifier Calls : {stats['total_calls']}")
    click.echo(f"Pass Rate            : {stats['pass_rate']:.1%}")
    click.echo(f"Mean Reward          : {stats['mean_reward']:.3f}")
    click.echo(f"Ceiling Rate (>=1.0) : {stats['ceiling_rate']:.1%}")
    click.echo(f"Exceptions Caught    : {stats['exception_count']}")
    click.echo(f"Avg Latency          : {stats['avg_duration_ms']} ms")

    if stats.get("warning_flag"):
        click.echo("\n⚠️  WARNING: >85% of rollout steps hit max reward ceiling! Possible reward shortcut.", err=True)


@main.command(name="ui")
@click.argument("path", type=click.Path(exists=True), default=".")
@click.option("--port", "-p", type=int, default=8500, help="Port to run the UI server on (default: 8500).")
def ui_cmd(path: str, port: int):
    """Launch the interactive web dashboard UI in your browser."""
    from ratctl.ui import launch_dashboard

    launch_dashboard(path=path, port=port)


@main.command(name="dashboard")
@click.argument("path", type=click.Path(exists=True), default=".")
@click.option("--port", "-p", type=int, default=8500, help="Port to run the UI server on (default: 8500).")
def dashboard_cmd(path: str, port: int):
    """Launch the interactive web dashboard UI in your browser (alias for ratctl ui)."""
    from ratctl.ui import launch_dashboard

    launch_dashboard(path=path, port=port)


@main.command(name="tui")
@click.argument("log_path", type=click.Path(), default="logs/run.jsonl")
@click.option("--no-live", is_flag=True, help="Render a single frame snapshot without full-screen live updates.")
def tui_cmd(log_path: str, no_live: bool):
    """Launch the live interactive Terminal UI (TUI) dashboard."""
    from ratctl.tui import run_tui

    run_tui(log_path=log_path, live_mode=not no_live)



def _parse_threshold(fail_on: str) -> float | None:
    """Parse a --fail-on expression like 'gameability>0.3'."""
    match = re.match(r"gameability\s*>\s*([0-9]*\.?[0-9]+)", fail_on)
    if match:
        return float(match.group(1))
    click.echo(
        f"Warning: Could not parse --fail-on '{fail_on}'. "
        "Expected format: 'gameability>0.3'",
        err=True,
    )
    return None


if __name__ == "__main__":
    main()

